# This is a hack to make VTK work. TODO: find another way to suppress the built-in find module.
if(PROJECT_NAME STREQUAL "VTK")
    _find_package(${ARGV})
else()
    _find_package(${ARGV} CONFIG)
    # Fill in missing static/shared targets
    foreach(HDF5TARGET hdf5 hdf5_hl hdf5_cpp hdf5_hl_cpp)
        if(TARGET hdf5::${HDF5TARGET}-static AND NOT TARGET hdf5::${HDF5TARGET}-shared)
            _add_library(hdf5::${HDF5TARGET}-shared INTERFACE IMPORTED)
            set_target_properties(hdf5::${HDF5TARGET}-shared PROPERTIES INTERFACE_LINK_LIBRARIES "hdf5::${HDF5TARGET}-static")
        elseif(TARGET hdf5::${HDF5TARGET}-shared AND NOT TARGET hdf5::${HDF5TARGET}-static)
            _add_library(hdf5::${HDF5TARGET}-static INTERFACE IMPORTED)
            set_target_properties(hdf5::${HDF5TARGET}-static PROPERTIES INTERFACE_LINK_LIBRARIES "hdf5::${HDF5TARGET}-shared")
        endif()
        if(TARGET hdf5::${HDF5TARGET}-static AND NOT TARGET ${HDF5TARGET}-static)
            _add_library(${HDF5TARGET}-static INTERFACE IMPORTED)
            set_target_properties(${HDF5TARGET}-static PROPERTIES INTERFACE_LINK_LIBRARIES "hdf5::${HDF5TARGET}-static")
        endif()
        if(TARGET hdf5::${HDF5TARGET}-shared AND NOT TARGET ${HDF5TARGET}-shared)
            _add_library(${HDF5TARGET}-shared INTERFACE IMPORTED)
            set_target_properties(${HDF5TARGET}-shared PROPERTIES INTERFACE_LINK_LIBRARIES "hdf5::${HDF5TARGET}-shared")
        endif()
    endforeach()
endif()
